### ISSUE TITLE
TOC links are wrong when chapter names are duplicated

### ISSUE THREAD

**Issue by genmeblog** [nextjournal/clerk#193] opened 2022-07-12 09:53 UTC
When there are the same chapter names in the document, TOC links are created for the first one.

See `Custom scales` chapters in https://scicloj.github.io/wadogo/index.html

**Comment by mk** [comment] 2023-02-10 17:16
This was fixed in #336.

#330 should have been marked as a duplicate of this one.

**Closed by mk** 2023-02-10 17:16 UTC
