### ISSUE TITLE
Exception thrown when trying to use specter's select fn

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/clerk#286] opened 2022-11-18 07:41 UTC
Hi,

there appears to be a problem when trying to use [specter](https://github.com/redplanetlabs/specter)'s [select](https://cljdoc.org/d/com.rpl/specter/1.1.4/api/com.rpl.specter#select) function, clerk throws an error complainging about a var that specter probably creates internally:

```
Unhandled clojure.lang.ExceptionInfo
The var `#'issue/pathcache22778` exists at runtime, but Clerk cannot find it in the namespace. Did you remove it?
{:file 
"
src/issue.clj"
 :form (s/select (s/walker number?) {:a 1}) :var-name issue/pathcache22778}
```

The expectation is that clerk should be able to handle any clj library gracefully.

To reproduce
1. Create  a deps.edn project with clerk and specter:
```clojure
{:deps {io.github.nextjournal/clerk {:mvn/version "0.11.603"}
        com.rpl/specter {:mvn/version "1.1.4"}}}
```
2. Create a clj file to display as a clerk notebook that calls on specter's `select` fn
```clojure
(ns issue
  (:require [com.rpl.specter :as s]
            [nextjournal.clerk :as clerk]))

;; the below will collect all numbers in the collection into a vector
(s/select (s/walker number?)
          {:a 1})
```
3. Try to `show!` the clj file in clerk, the above error is thrown.

`select` ref: https://github.com/redplanetlabs/specter/blob/67e86806020b9d02fbca8cdb1efad3002fc81a32/src/clj/com/rpl/specter.cljc#L347

Thanks

**Comment by jackrusher** [comment] 2022-11-18 08:33
This is a duplicate of issue 247. Clerk currently has trouble with libraries that add vars without using `def` or similar.

**Closed by jackrusher** 2022-11-18 08:33 UTC
Labels: duplicate
