### ISSUE TITLE
Does not work when no internet

### ISSUE THREAD

**Issue by rynkowsg** [nextjournal/clerk#112] opened 2022-03-14 16:08 UTC
What do you think about embedding all the JS/CSS deps? The main reason why I ask about that is that at the moment it is not possible to load the clerk page when there is no internet connection 😬 

![Screen Shot 2022-03-14 at 16 05 37](https://user-images.githubusercontent.com/5878299/158213180-1336c8ae-143b-46f7-ae55-e8aa04a545c2.png)

**Comment by mk** [comment] 2022-03-14 18:05
Yep, this is a duplicate of #30 and something we're thinking about, see https://github.com/nextjournal/clerk/issues/30#issuecomment-999085787

**Closed by mk** 2022-03-14 18:05 UTC
