### ISSUE TITLE
Java Path value causes non-termination error in clerk/show!

### ISSUE THREAD

**Issue by respatialized** [nextjournal/clerk#199] opened 2022-08-11 22:20 UTC
Previously reported on [Clojurians](https://clojurians.slack.com); recording here for posterity as requested by @mk.

# Description
Using `java.nio.Path` objects as values in a notebook causes a notebook to never successfully evaluate. It never reaches the `Clerk evaluated 'src/clerk_errors.clj' in ... ms` step.

# Expected behavior
The notebook renders correctly using the string representation of a `Path`. Failing that, an error message is at least thrown somewhere so I don't have to manually interrupt notebook evaluation.

# Reproducing the issue

```clojure
(ns clerk-errors
  (:require [clojure.java.io :as io]
            [babashka.fs :as fs]
            [nextjournal.clerk :as clerk]))

;; Notebook demonstrating errors Clerk has with Java values
;;

;; # `Path`

(str (fs/path "something"))
(with-out-str (println (fs/path "something")))
;; String and printed representations work fine; the `Path` itself will cause values to hang.
; (fs/path "something")

```
If the above `fs/path` call is uncommented and evaluated with `clerk/show!`, the notebook hangs, never evaluating. Regular evaluation works fine.

**Comment by respatialized** [comment] 2022-08-11 22:23
@jackrusher also asked if I observe any browser console errors when this happens. I haven't seen any alongside this issue, in part because it doesn't seem to me like values are even getting across the JVM <> notebook boundary.

**Comment by mk** [comment] 2022-08-12 07:16
@respatialized thanks for the report, I can reproduce it on my end.

**Comment by mk** [comment] 2022-08-15 09:50
The problem is `nextjournal.clerk.analyzer/exceeds-bounded-count-limit?` never terminating when getting a path:
https://github.com/nextjournal/clerk/blob/80c646d892d4d81a3e1b2832c713a3f50e43dbc2/src/nextjournal/clerk/analyzer.clj#L368-L378


See
```clojure
(seq (.toPath (clojure.java.io/file "something")));;=> (#object[sun.nio.fs.UnixPath 0x5aa4c178 "something"])

(take 10 (tree-seq seqable? seq (.toPath (clojure.java.io/file "something"))))
;;=> (#object[sun.nio.fs.UnixPath 0x7307e110 "something"] #object[sun.nio.fs.UnixPath 0x35cacee7 "something"] #object[sun.nio.fs.UnixPath 0x3de508 "something"] #object[sun.nio.fs.UnixPath 0x4c185902 "something"] #object[sun.nio.fs.UnixPath 0xdb3ef0 "something"] #object[sun.nio.fs.UnixPath 0x630565fa "something"] #object[sun.nio.fs.UnixPath 0xc7fc937 "something"] #object[sun.nio.fs.UnixPath 0x22141f3 "something"] #object[sun.nio.fs.UnixPath 0x5b54d3f9 "something"] #object[sun.nio.fs.UnixPath 0x13b647dc "something"])
```

**Comment by mk** [comment] 2022-08-16 13:20
@respatialized the issue should be fixed with the commit above which just landed in `main`. Thanks again for the report.

**Closed** 2022-08-16 13:19 UTC
