### ISSUE TITLE
Invalid LaTeX math appears to cause the Clerk browser UI to crash

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/clerk#603] opened 2024-01-07 13:42 UTC
Hi!

It looks like invalid LaTeX math causes Clerk to Crash. Perhaps it's possible to provide an error message.

## Repro

Clerk version: `io.github.nextjournal/clerk {:mvn/version "0.15.957"}`

Put this in a Clojure file, then evaluate:

```
;; But for $\mathup{mm}^3$
```

(the correct LaTeX math appears to be `$\mathrm{mm}^3$`)

## Expected

An error message pointing out the invalid LaTeX math

## Actual

I'm seeing a blank browser window. In the console, I get this error (on `io.github.nextjournal/clerk {:mvn/version "0.15.957"}`:

```
{"message": "KaTeX parse error: Undefined control sequence: \\mathup at position 1: \\̲m̲a̲t̲h̲u̲p̲{mm}^3", "data": {"meta": null, "N": 6, "K": [{"ns": null, "name": "type", "T": "type", "Bd": 1174270348, "J": 2153775105, "O": 4096}, {"ns": "sci", "name": "error", "T": "sci/error", "Bd": -979082803, "J": 2153775105, "O": 4096}, {"ns": null, "name": "line", "T": "line", "Bd": 212345235, "J": 2153775105, "O": 4096}, 1, {"ns": null, "name": "column", "T": "column", "Bd": 2078222095, "J": 2153775105, "O": 4096}, 469, {"ns": null, "name": "message", "T": "message", "Bd": -406056002, "J": 2153775105, "O": 4096}, "KaTeX parse error: Undefined control sequence: \\mathup at position 1: \\̲m̲a̲t̲h̲u̲p̲{mm}^3", {"ns": "sci.impl", "name": "callstack", "T": "sci.impl/callstack", "Bd": -1621010557, "J": 2153775105, "O": 4096}, {"state": {"meta": null, "first": {"meta": null, "N": 5, "K": [{"ns": null, "name": "line", "T": "line", "Bd": 212345235, "J": 2153775105, "O": 4096}, 1, {"ns": null, "name": "column", "T": "column", "Bd": 2078222095, "J": 2153775105, "O": 4096}, 469, {"ns": null, "name": "ns", "T": "ns", "Bd": 441598760, "J": 2153775105, "O": 4096}, {"name": {"ns": null, "name": "repro.invalid-math", "str": "repro.invalid-math", "Bd": -1724818465, "hc": null, "J": 2154168321, "O": 4096}, "meta": null, "J": 131072, "O": 0}, {"ns": null, "name": "file", "T": "file", "Bd": -1269645878, "J": 2153775105, "O": 4096}, null, {"ns": "sci.impl", "name": "f-meta", "T": "sci.impl/f-meta", "Bd": -1735495322, "J": 2153775105, "O": 4096}, {"meta": null, "N": 3, "K": [{"ns": null, "name": "arglists", "T": "arglists", "Bd": 1661989754, "J": 2153775105, "O": 4096}, {"meta": null, "first": {"meta": null, "N": 2, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "tex-string", "str": "tex-string", "Bd": 1817259250, "hc": null, "J": 2154168321, "O": 4096}, {"meta": null, "N": 1, "K": [{"ns": null, "name": "keys", "T": "keys", "Bd": 1068423698, "J": 2153775105, "O": 4096}, {"meta": null, "N": 1, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "inline?", "str": "inline?", "Bd": -33952264, "hc": null, "J": 2154168321, "O": 4096}], "I": null, "J": 167666463, "O": 139268}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 167666463, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, {"ns": null, "name": "ns", "T": "ns", "Bd": 441598760, "J": 2153775105, "O": 4096}, {"name": {"ns": null, "name": "nextjournal.clerk.render", "str": "nextjournal.clerk.render", "Bd": -459577755, "hc": null, "J": 2154168321, "O": 4096}, "meta": null, "J": 131072, "O": 0}, {"ns": null, "name": "name", "T": "name", "Bd": 1843675177, "J": 2153775105, "O": 4096}, {"ns": null, "name": "render-katex", "str": "render-katex", "Bd": 1429252316, "hc": {"meta": null, "N": 1, "K": [{"ns": null, "name": "arglists", "T": "arglists", "Bd": 1661989754, "J": 2153775105, "O": 4096}, {"meta": null, "first": {"ns": null, "name": "quote", "str": "quote", "Bd": 1377916282, "hc": null, "J": 2154168321, "O": 4096}, "rest": {"meta": null, "first": {"meta": null, "first": {"meta": null, "N": 2, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "tex-string", "str": "tex-string", "Bd": 1817259250, "hc": null, "J": 2154168321, "O": 4096}, {"meta": null, "N": 1, "K": [{"ns": null, "name": "keys", "T": "keys", "Bd": 1068423698, "J": 2153775105, "O": 4096}, {"meta": null, "N": 1, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "inline?", "str": "inline?", "Bd": -33952264, "hc": null, "J": 2154168321, "O": 4096}], "I": null, "J": 167666463, "O": 139268}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 167666463, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "count": 2, "I": null, "J": 65937646, "O": 8192}], "I": null, "J": 16647951, "O": 139268}, "J": 2154168321, "O": 4096}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 16647951, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "J": 32768, "O": 0}, {"ns": null, "name": "file", "T": "file", "Bd": -1269645878, "J": 2153775105, "O": 4096}, null], "I": null, "J": 16647951, "O": 139268}, "cause": {}, "name": "Error", "fileName": "https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true", "lineNumber": 2438, "columnNumber": 103, "stack": "Lk@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2438:103\nSl.v@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:3817:298\nLD/<@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2866:172\nLD@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2866:181\nVF/<@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:3043:14\nX@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2852:80\nxra/<@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2934:378\ng.h@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:5421:404\nkba@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2377:319\nlba@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2377:254\n$g.h@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:3399:121\npna@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2726:191\nqna@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2727:115\nrna/<@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2728:109\naw@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2667:40\nWla@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2671:371\nrna@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2728:87\nc@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2728:249\nO@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1787:297\nDe@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1805:113\nbl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1930:376\nHe@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1874:503\nZd@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1874:355\nma@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1867:110\nN@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1865:77\nl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1681:109\nY@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1681:475\nEventHandlerNonNull*shadow$provide[93]@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1683:379\nzl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:265\nshadow$provide[95]@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1688:52\nzl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:265\nshadow$provide[96]@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1893:332\nzl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:265\nshadow$provide[98]@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1946:259\nzl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:265\nshadow$provide[99]@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:1947:44\nzl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:265\nAl@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:2443:489\n@https://storage.clerk.garden/nextjournal/clerk-assets@3mwzShgnuyfhgFN9ahRYKqV32K11/viewer.js?immutable=true:4718:289\n"}
```

Error on `io.github.nextjournal/clerk {:git/sha "65988e062c8e9dc5e48111d05fec5350cf80e4c9"}`:

```
{"message": "KaTeX parse error: Undefined control sequence: \\mathup at position 1: \\̲m̲a̲t̲h̲u̲p̲{mm}^3", "data": {"meta": null, "N": 6, "K": [{"ns": null, "name": "type", "T": "type", "Bd": 1174270348, "J": 2153775105, "O": 4096}, {"ns": "sci", "name": "error", "T": "sci/error", "Bd": -979082803, "J": 2153775105, "O": 4096}, {"ns": null, "name": "line", "T": "line", "Bd": 212345235, "J": 2153775105, "O": 4096}, 1, {"ns": null, "name": "column", "T": "column", "Bd": 2078222095, "J": 2153775105, "O": 4096}, 2798, {"ns": null, "name": "message", "T": "message", "Bd": -406056002, "J": 2153775105, "O": 4096}, "KaTeX parse error: Undefined control sequence: \\mathup at position 1: \\̲m̲a̲t̲h̲u̲p̲{mm}^3", {"ns": "sci.impl", "name": "callstack", "T": "sci.impl/callstack", "Bd": -1621010557, "J": 2153775105, "O": 4096}, {"state": {"meta": null, "first": {"meta": null, "N": 5, "K": [{"ns": null, "name": "line", "T": "line", "Bd": 212345235, "J": 2153775105, "O": 4096}, 1, {"ns": null, "name": "column", "T": "column", "Bd": 2078222095, "J": 2153775105, "O": 4096}, 2798, {"ns": null, "name": "ns", "T": "ns", "Bd": 441598760, "J": 2153775105, "O": 4096}, {"name": {"ns": null, "name": "repro.invalid-math", "str": "repro.invalid-math", "Bd": -1724818465, "hc": null, "J": 2154168321, "O": 4096}, "meta": null, "J": 131072, "O": 0}, {"ns": null, "name": "file", "T": "file", "Bd": -1269645878, "J": 2153775105, "O": 4096}, null, {"ns": "sci.impl", "name": "f-meta", "T": "sci.impl/f-meta", "Bd": -1735495322, "J": 2153775105, "O": 4096}, {"meta": null, "N": 3, "K": [{"ns": null, "name": "arglists", "T": "arglists", "Bd": 1661989754, "J": 2153775105, "O": 4096}, {"meta": null, "first": {"meta": null, "N": 2, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "tex-string", "str": "tex-string", "Bd": 1817259250, "hc": null, "J": 2154168321, "O": 4096}, {"meta": null, "N": 1, "K": [{"ns": null, "name": "keys", "T": "keys", "Bd": 1068423698, "J": 2153775105, "O": 4096}, {"meta": null, "N": 1, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "inline?", "str": "inline?", "Bd": -33952264, "hc": null, "J": 2154168321, "O": 4096}], "I": null, "J": 167666463, "O": 139268}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 167666463, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, {"ns": null, "name": "ns", "T": "ns", "Bd": 441598760, "J": 2153775105, "O": 4096}, {"name": {"ns": null, "name": "nextjournal.clerk.render", "str": "nextjournal.clerk.render", "Bd": -459577755, "hc": null, "J": 2154168321, "O": 4096}, "meta": null, "J": 131072, "O": 0}, {"ns": null, "name": "name", "T": "name", "Bd": 1843675177, "J": 2153775105, "O": 4096}, {"ns": null, "name": "render-katex", "str": "render-katex", "Bd": 1429252316, "hc": {"meta": null, "N": 1, "K": [{"ns": null, "name": "arglists", "T": "arglists", "Bd": 1661989754, "J": 2153775105, "O": 4096}, {"meta": null, "first": {"ns": null, "name": "quote", "str": "quote", "Bd": 1377916282, "hc": null, "J": 2154168321, "O": 4096}, "rest": {"meta": null, "first": {"meta": null, "first": {"meta": null, "N": 2, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "tex-string", "str": "tex-string", "Bd": 1817259250, "hc": null, "J": 2154168321, "O": 4096}, {"meta": null, "N": 1, "K": [{"ns": null, "name": "keys", "T": "keys", "Bd": 1068423698, "J": 2153775105, "O": 4096}, {"meta": null, "N": 1, "shift": 5, "root": {"La": null, "K": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}, "tail": [{"ns": null, "name": "inline?", "str": "inline?", "Bd": -33952264, "hc": null, "J": 2154168321, "O": 4096}], "I": null, "J": 167666463, "O": 139268}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 167666463, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "count": 2, "I": null, "J": 65937646, "O": 8192}], "I": null, "J": 16647951, "O": 139268}, "J": 2154168321, "O": 4096}], "I": null, "J": 16647951, "O": 139268}], "I": null, "J": 16647951, "O": 139268}, "rest": null, "count": 1, "I": null, "J": 65937646, "O": 8192}, "J": 32768, "O": 0}, {"ns": null, "name": "file", "T": "file", "Bd": -1269645878, "J": 2153775105, "O": 4096}, null], "I": null, "J": 16647951, "O": 139268}, "cause": {}, "name": "Error", "fileName": "https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true", "lineNumber": 2439, "columnNumber": 103, "stack": "Lk@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2439:103\nSl.v@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:3823:298\nLD/<@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2867:172\nLD@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2867:181\nVF/<@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:3044:14\nX@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2853:80\nxra/<@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2935:378\ng.h@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:5434:404\nkba@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2378:319\nlba@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2378:254\n$g.h@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:3405:121\npna@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2727:191\nqna@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2728:115\nrna/<@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2729:109\naw@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2667:488\nWla@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2672:357\nrna@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2729:87\nc@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:2729:249\nO@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1788:297\nDe@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1806:113\nbl@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1931:376\nHe@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1875:503\nZd@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1875:355\nma@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1868:110\nN@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1866:77\nl@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1682:109\nY@https://storage.clerk.garden/nextjournal/clerk-assets@hFdvxfue93m7p5AMmZn7PfFFaA4/viewer.js?immutable=true:1682:475\n"}
```

Screenshot:

![image](https://github.com/nextjournal/clerk/assets/5285452/d66eaff0-9ddb-4106-8498-8fd3cc1587ca)

I have to do a browser refresh to get Clerk reloading to work again.

## Closing

And as always, thanks for Clerk. It's really changing how I'm working with code, even non-Clojure code. Being able to make the inteface I need to see what I need to see is great.

Teodor

**Comment by zampino** [comment] 2024-01-08 09:57
Thanks for the report. It seems it's a duplicate of #571. Sorry for keeping that around for months!

**Closed** 2024-01-08 16:18 UTC
