### ISSUE TITLE
table-viewer does not pass page size to table-body-viewer

### ISSUE THREAD

**Issue by behrica** [nextjournal/clerk#313] opened 2022-12-04 20:44 UTC
so this is not working:

```clojure
(v/with-viewer
  (assoc v/table-viewer :page-size 3)
  (seq (tc/rows all-data :as-maps)))
```
The table body gets still rendered with page-size 20

**Comment by mk** [comment] 2022-12-04 21:07
Indeed this is a duplicate of #313.

**Closed by mk** 2022-12-04 21:07 UTC
